### PR TITLE
Delete code of abandoned equinox-io, -ip, -util and -wireadmin plug-ins

### PR DESCRIPTION
**Pull request by HannesWell**
As suggested in https://github.com/eclipse-equinox/equinox.framework/issues/40#issuecomment-1103079571 this PR deletes the following plug-ins that are not build for a while:
- org.eclipse.equinox.io
- org.eclipse.equinox.ip
- org.eclipse.equinox.util
- org.eclipse.equinox.wireadmin

Some background why they have been abandoned can be found here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=533801

### CODE REVIEW

**Comment by HannesWell** [comment]
From the from the `equinox.bundles/pom.xml` I dereived that there are some more bundles that are not build and not published anymore:

- org.eclipse.equinox.ds
- org.eclipse.equinox.http (https://bugs.eclipse.org/bugs/show_bug.cgi?id=389050)
- org.eclipse.equinox.servletbridge.extensionbundle (background: https://bugs.eclipse.org/bugs/show_bug.cgi?id=348045)

The same applies for the feature:
- org.eclipse.equinox.server.servletbridge (https://bugs.eclipse.org/bugs/show_bug.cgi?id=348045)

Could they be deleted too?

**Comment by tjwatson** [comment]
> From the from the `equinox.bundles/pom.xml` I derived that there are one more bundle and feature that are not build and not published anymore:
> 
> * org.eclipse.equinox.servletbridge.extensionbundle (background: https://bugs.eclipse.org/bugs/show_bug.cgi?id=348045)
> * org.eclipse.equinox.server.servletbridge (https://bugs.eclipse.org/bugs/show_bug.cgi?id=348045)
> 
> Could they be deleted too?

Yes, I see no reason to leave stuff we don't build here.

**Comment by HannesWell** [comment]
> > * org.eclipse.equinox.servletbridge.extensionbundle (background: https://bugs.eclipse.org/bugs/show_bug.cgi?id=348045)
> > * org.eclipse.equinox.server.servletbridge (https://bugs.eclipse.org/bugs/show_bug.cgi?id=348045)
> > 
> > Could they be deleted too?
> 
> Yes, I see no reason to leave stuff we don't build here.

Great!

Besides the mentioned ones I think `bundles/org.eclipse.equinox.servletbridge.template` should removed as well. 
In contrast to the others it is build at the moment, but it was not published. And since it only consists of a product template that uses plug-ins and features that are finally removed with this PR I think it can/should go as well.

Removing the servletbridge.extension bundl also allowed to simplify the poms of some test plugins.

Furthermore the method `deployExtensionBundle(File)` in `org.eclipse.equinox.servletbridge.FrameworkLauncher` could be simplified since we now know that `org.eclipse.equinox.servletbridge.extensionbundle` can never be found. But I think this should go into a dedicated issue.

**Comment by tjwatson** [comment]
> Furthermore the method `deployExtensionBundle(File)` in `org.eclipse.equinox.servletbridge.FrameworkLauncher` could be simplified since we now know that `org.eclipse.equinox.servletbridge.extensionbundle` can never be found. But I think this should go into a dedicated issue.

Yes, separate issue.  Not sure we should do that though because one can always have packaged their own JAR with that name in their WAR.

**Comment by HannesWell** [comment]
After systematically going through all projects I found two more abandoned projects:
- bundles/org.eclipse.equinox.compendium.tests
- bundles/org.eclipse.equinox.http.jetty.starter

So the full list of removed projects is:
- bundles/org.eclipse.equinox.io
- bundles/org.eclipse.equinox.ip
- bundles/org.eclipse.equinox.util
- bundles/org.eclipse.equinox.wireadmin
- bundles/org.eclipse.equinox.servletbridge.extensionbundle
- bundles/org.eclipse.equinox.servletbridge.template
- bundles/org.eclipse.equinox.compendium.tests
- bundles/org.eclipse.equinox.http.jetty.starter
- features/org.eclipse.equinox.server.servletbridge

Where only `org.eclipse.equinox.servletbridge.template` is build but not published at the moment but as mentioned above I think it is obsolete.

**Comment by HannesWell** [comment]
@tjwatson are you fine with removing them all?

> > Furthermore the method `deployExtensionBundle(File)` in `org.eclipse.equinox.servletbridge.FrameworkLauncher` could be simplified since we now know that `org.eclipse.equinox.servletbridge.extensionbundle` can never be found. But I think this should go into a dedicated issue.
> 
> Yes, separate issue. Not sure we should do that though because one can always have packaged their own JAR with that name in their WAR.

OK. Then lest leave it as it is. Less work to do. :)

**Comment by HannesWell** [comment]
@tjwatson are you fine with this PR as it is now?
If yes I would like to submit it.

**Comment by tjwatson** [comment]
> @tjwatson are you fine with this PR as it is now? If yes I would like to submit it.

Can we not delete the two test projects?   The `compendium.tests` don't exist anywhere else and I use them to test locally (although I would like to get them enabled in the build also for testing things like metatype impl).  The `ds.tests` is questionable to keep but I have used that to verify that our updates to felix SCR versions are working correctly within the project.

**Comment by tjwatson** [comment]
For the record, I will state that the OSGi WG currently uses the Equinox wireadmin implementation as the compatible implementation.  But the wireadmin specification has not seen an update in since its very first 1.0 version release.  I argue the OSGi WG can continue to use the currently released versions of Equinox wireadmin for a compatible implementation.

I've literally not heard a single thing from when we stopped building the wireadmin implementation over two years ago. (https://bugs.eclipse.org/bugs/show_bug.cgi?id=533801).  That makes me think nobody uses our implementation of wireadmin except the OSGi WG as the compatible implementation to release the wireadmin specification.

**Comment by tjwatson** [comment]
I forgot to mention that the `ds.tests` are currently executed during our I-Builds.  So deleting them may require other releng work first.

**Comment by akurtakov** [comment]
ds.tests are executed and I kind of assumed they are testing felix.scr integration on our side, is this not the case?

**Comment by tjwatson** [comment]
> ds.tests are executed and I kind of assumed they are testing felix.scr integration on our side, is this not the case?

Yes, that is the case and why I think we should not delete them at this time.

**Comment by HannesWell** [comment]
> > @tjwatson are you fine with this PR as it is now? If yes I would like to submit it.
> 
> ~Can we~ Do not delete the two test projects.~?~ The `compendium.tests` don't exist anywhere else and I use them to test locally (although I would like to get them enabled in the build also for testing things like metatype impl). The `ds.tests` is questionable to keep but I have used that to verify that our updates to felix SCR versions are working correctly within the project.

The project `ds.tests` was never deleted. It was only modified to remove the reference to `org.eclipse.equinox.util` that is about to be removed with this PR.
But I reverted the modifications to remove non-Java references to the removed plugin and will submit them in a separate PR so that this is a clean delete only PR.

I also reverted the remove of `compendium.tests`. The reason I collected all projects that are not build and not only the one you mentioned in https://github.com/eclipse-equinox/equinox.framework/issues/40#issuecomment-1103079571 is that I would like to enabled and fully leverage Tycho-pomless for this repo later. I created a separate PR to include `compendium.tests`.

This avoids the need to list each plugin to build in the root pom but instead just build everything in the `bundles` and `features` directory...

But while typing those lines I start to question if Tycho can also generate the aggregator pom's in the aggregator build?
@akurtakov can we Tycho's automatic aggregator-pom generation for projects that are part of the aggregator build? It will work when I 'build-individual-bundles' but will it also work in an I-build?

**Comment by HannesWell** [comment]
> For the record, I will state that the OSGi WG currently uses the Equinox wireadmin implementation as the compatible implementation. But the wireadmin specification has not seen an update in since its very first 1.0 version release. I argue the OSGi WG can continue to use the currently released versions of Equinox wireadmin for a compatible implementation.
> 
> I've literally not heard a single thing from when we stopped building the wireadmin implementation over two years ago. (https://bugs.eclipse.org/bugs/show_bug.cgi?id=533801). That makes me think nobody uses our implementation of wireadmin except the OSGi WG as the compatible implementation to release the wireadmin specification.

So could when then keep it as well? If yes I suggest to start building it again.

**Comment by tjwatson** [comment]
> So could when then keep it as well? If yes I suggest to start building it again.

No, I am for removing that source code for the wireadmin impl.  If the OSGi WG chooses to progress the wireadmin specification then there should be someone with interest to actually implement it also.  At that time we can re-evaluate getting the source backup and running if the interest is to implement at Equinox.

> The project `ds.tests` was never deleted.

Ah, sorry I didn't notice that.  OK, I see that it has some benign code that tries to find the `org.eclipse.equinox.util` bundle in the test.  I guess we can leave that there and remove the reference later.

**Comment by HannesWell** [comment]
Great! Thanks Tom for the review.

**Pull request merged**
