### PR TITLE
Remove 'o.e.equinox.serverside.sdk' feature (and stop building and publishing it)

### PR DESCRIPTION
**Pull request by HannesWell**
As discussed in https://github.com/eclipse-equinox/equinox.bundles/pull/42#issuecomment-1117623651 there is now known use-case for the `org.eclipse.equinox.serverside.sdk` and because it makes the project maintenance more difficult (due to its cross-repository plug-in inclusions) this feature is proposed for removal.

Please speak up as soon as possible if you use that feature and describe your use-case.

In case nobody raises objections we will proceed with the removal
Do we need PMC approval for this? If necessary, @tjwatson, @vogella please discuss this at the next PMC-meeting.

### CODE REVIEW

**Comment by HannesWell** [comment]
Announced the removal at the `equinox-dev` mailing-list:
https://www.eclipse.org/lists/equinox-dev/msg09419.html

**Comment by mknauer** [comment]
It is currently required by our target definition that we are using to build the [Eclipse RAP](https://github.com/eclipse-rap) Tools project

[org.eclipse.rap.tools.target.definition.target](https://github.com/eclipse-rap/org.eclipse.rap.tools/blob/31e86a29fc4868bf4d844e5f6aea1fa6fc2ef187/releng/org.eclipse.rap.tools.build/target.definition/org.eclipse.rap.tools.target.definition.target#L23):
```xml
            <unit id="org.eclipse.equinox.serverside.sdk.feature.group" version="3.23.400.v20220428-0821"/>
```
and will require some work to remove it. Please let us know in advance before merging this PR.

**Comment by mickaelistria** [comment]
@mknauer Are you actually using this feature or can RAP just stop consuming it? If RAP needs it and seems to be the only consumer, wouldn't it be better that you move this feature into RAP's code?

**Comment by mknauer** [comment]
Using: yes
Stopping consuming it: possible

I was just asking to get an early heads-up before you are merging this PR, not questioning its removal, because it means some work for me.

**Comment by mickaelistria** [comment]
> I was just asking to get an early heads-up before you are merging this PR

I think this is the heads-up; the goal would be to merge this PR as soon as it's ready -it could be later today!-; so the sooner RAP can cope with it the better.

**Comment by mknauer** [comment]
Done. Dependency of the RAP project has been removed.

**Comment by mickaelistria** [comment]
Great, thanks @mknauer !

**Comment by mickaelistria** [comment]
@HannesWell Anything left to do here? Would be nice to merge it soon.

**Comment by HannesWell** [comment]
> @HannesWell Anything left to do here? Would be nice to merge it soon.

Technically this is ready for submission. The only question is if this removal requires a special approval (although I expect it will be granted since @vogella and @tjwatson expressed their consent in PR #42)?

**Comment by HannesWell** [comment]
> > if this removal requires a special approval
> 
> I think it's all good, with public announce on the mailing list and with 1 Project Lead and 2 PMC member approvals.

Alright, then lets merge this. :)

FYI, I won't be available tomorrow, so if this requires more changes somewhere else in the platform to make the I-build succeed I want to ask you to take care of them.

**Comment by HannesWell** [comment]
Should we mention the removal in the migration-guide or similar?
And if so, where exactly do I have to do this?

**Comment by vogella** [comment]
> Should we mention the removal in the migration-guide or similar? And if so, where exactly do I have to do this?

Mentioning should not be necessary IMHO. If you want you can add to the N&N.

**Comment by mickaelistria** [comment]
Migration guide is at https://github.com/eclipse-platform/eclipse.platform.common/tree/0effdecb3a20c5be80642c874adf318b8199d4b5/bundles/org.eclipse.platform.doc.isv/porting/4.24

**Comment by HannesWell** [comment]
I was preparing an entry in the migration but started to get the impression that the migration guide is for more heavy weight incompatibilities like major API changes. On the other hand my impression is that N&N mostly contains cool new features to advertise the new release. I think the removal of this feature is not such cool interesting item. 😅
 
I think we should definitely announce it but I'm not sure where the best place is.

Could you clarify what the exact difference between N&N and migration guide is and what the target-audience is?

**Comment by vogella** [comment]
The API migration guide for planned API removals. The N&N is to inform users about notable changes. As features not not API, I think it is more interesting for N&N if at all.

**Comment by tjwatson** [comment]
I find it hard to think of removal of a feature as N&N to any user.  That really feels like migration guide material.  You say they are not API, but I am sure lots of consumers would disagree if we removed the RCP feature or any other that is heavily depended on.

**Comment by HannesWell** [comment]
> I find it hard to think of removal of a feature as N&N to any user. That really feels like migration guide material. You say they are not API, but I am sure lots of consumers would disagree if we removed the RCP feature or any other that is heavily depended on.

Agree on this.
I created an migration guide entry:
https://github.com/eclipse-platform/eclipse.platform.common/pull/20
Feel free to add your comments.



> > I have no strong opinion on this...........
> 
> Well since you put it that way, I have no strong opinion either :)
> 
> But an opinion was asked for.

Even if opinions are not strong they can still be helpful. Thanks.

**Comment by HannesWell** [comment]
> Agree on this. I created an migration guide entry: [eclipse-platform/eclipse.platform.common#20](https://github.com/eclipse-platform/eclipse.platform.common/pull/20) Feel free to add your comments.

Since there were no objections I submitted it.

**Pull request merged**
